name:     sleep
version:  0.1.0
synopsis: A collection of REST API clients
github:   nicuveo/sleep


ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fwarn-tabs
  - -fno-warn-type-defaults
  - -pgmL markdown-unlit

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - authenticate-oauth
  - bytestring
  - containers
  - data-has
  - http-client
  - http-client-tls
  - http-conduit
  - http-types
  - mtl
  - network-uri
  - resourcet
  - safe-exceptions
  - text
  - time
  - transformers
  - transformers-base
  - uri-encode
  - vector


library:
  source-dirs: src


executables:
  tumblr-photo-download:
    source-dirs: apps/tpd
    main: Main.hs
    ghc-options:
      - -O2
      - -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - sleep
      - conduit
      - conduit-extra
      - directory
      - filepath
      - http-conduit
      - mtl
      - resourcet


tests:
  tumblr-tests:
    source-dirs:
      - tests/tumblr
      - src
    main: Tests.hs
    ghc-options:
      - -O2
      - -threaded -rtsopts -with-rtsopts=-N -fhpc
    dependencies:
      - QuickCheck
      - directory
      - filepath
      - tasty
      - tasty-hunit
      - tasty-quickcheck
